version: 2.1

jobs:
  serve_and_test:
    docker:
      - image: nikolaik/python-nodejs:python3.5-nodejs12
    working_directory: ~/app
    steps:
      - checkout
      - name: Installs cypress dependencies
        run: |
          apt-get update && \
          apt-get install -y \
          libgtk2.0-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          xvfb
      - name: Installs yarn dependencies
        run: yarn install
      - name: Installs flask and dependencies
        run: pip install -r requirements.txt
      - name: Serves flask app in the background
        run: python app.py >> nohup.log 2>&1 &
      - name: Runs cypress tests with yarn
        run: yarn cypress run

workflows:
  test_basic_html:
    jobs:
      - serve_and_test