version: 2.1

jobs:
  serve_and_test:
    docker:
      - image: nikolaik/python-nodejs:python3.5-nodejs12
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Installs cypress dependencies
          command: |
            apt-get update && \
            apt-get install -y \
            libgtk2.0-0 \
            libnotify-dev \
            libgconf-2-4 \
            libnss3 \
            libxss1 \
            libasound2 \
            xvfb
      - run:
          name: Installs packages with yarn
          command: yarn install
      - run:
          name: Installs flask and dependencies
          command: pip install -r requirements.txt
      - run:
          name: Serves flask app and runs cypress tests with yarn
          command: python app.py >> nohup.log 2>&1 & yarn cypress run
#      - run:
#          name: Runs cypress tests with yarn
#          command: yarn cypress run

workflows:
  test_basic_html:
    jobs:
      - serve_and_test